"""empty message

Revision ID: 17a6707d6913
Revises: 84b79b342ae8
Create Date: 2023-09-11 17:07:45.836372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a6707d6913'
down_revision = '84b79b342ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankDetailsID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('bankID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('bankDetailsID')

    # ### end Alembic commands ###
