"""empty message

Revision ID: 2db5f6aa9a2c
Revises: cb67f82ffaff
Create Date: 2023-09-11 14:27:34.205298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db5f6aa9a2c'
down_revision = 'cb67f82ffaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountType',
    sa.Column('accountTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accountName', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('accountTypeID')
    )
    op.create_table('Bank',
    sa.Column('bankID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bankName', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('bankID')
    )
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankDetailsID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('bankNameID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('accountTypeID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Bank', ['bankNameID'], ['bankID'])
        batch_op.create_foreign_key(None, 'AccountType', ['accountTypeID'], ['accountTypeID'])
        batch_op.drop_column('bankSortCode')
        batch_op.drop_column('bankName')
        batch_op.drop_column('bankCardNumber')
        batch_op.drop_column('bankIssueDate')
        batch_op.drop_column('bankID')
        batch_op.drop_column('bankExpiryDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankExpiryDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bankID', sa.INTEGER(), server_default=sa.text('nextval(\'"BankDetails_bankID_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('bankIssueDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bankCardNumber', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bankName', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bankSortCode', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('accountTypeID')
        batch_op.drop_column('bankNameID')
        batch_op.drop_column('bankDetailsID')

    op.drop_table('Bank')
    op.drop_table('AccountType')
    # ### end Alembic commands ###
