"""empty message

Revision ID: 2fda5e7e218e
Revises: 0c193c8fdc4f
Create Date: 2023-09-10 17:33:54.402348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fda5e7e218e'
down_revision = '0c193c8fdc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveLoan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentFrequencyID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ActiveLoan_paymentFrequency_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'PaymentFrequency', ['paymentFrequencyID'], ['paymentFrequencyID'])
        batch_op.drop_column('paymentFrequency')

    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentFrequencyID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('LoanOffer_paymentFrequency_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'PaymentFrequency', ['paymentFrequencyID'], ['paymentFrequencyID'])
        batch_op.drop_column('paymentFrequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentFrequency', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('LoanOffer_paymentFrequency_fkey', 'PaymentFrequency', ['paymentFrequency'], ['paymentFrequencyID'])
        batch_op.drop_column('paymentFrequencyID')

    with op.batch_alter_table('ActiveLoan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentFrequency', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ActiveLoan_paymentFrequency_fkey', 'PaymentFrequency', ['paymentFrequency'], ['paymentFrequencyID'])
        batch_op.drop_column('paymentFrequencyID')

    # ### end Alembic commands ###
