"""empty message

Revision ID: 30962fc020ec
Revises: a8589637df4e
Create Date: 2023-09-07 20:27:05.254011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30962fc020ec'
down_revision = 'a8589637df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LoanAdvertisement',
    sa.Column('loanAdvertisementID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Numeric(precision=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('loanAdvertisementID'),
    sa.UniqueConstraint('negotiable')
    )
    op.create_table('OfferStatus',
    sa.Column('offerStatusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('offerStatusID')
    )
    op.create_table('PaymentFrequency',
    sa.Column('paymentFrequencyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frequency', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('paymentFrequencyID')
    )
    op.create_table('PaymentStatus',
    sa.Column('paymentStatusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('paymentStatusID')
    )
    op.create_table('TransactionStatus',
    sa.Column('transactionStatusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('transactionStatusID')
    )
    op.create_table('LoanConditions',
    sa.Column('loanConditionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loanAdvertisementID', sa.Integer(), nullable=False),
    sa.Column('loanConditionDescription', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['loanAdvertisementID'], ['LoanAdvertisement.loanAdvertisementID'], ),
    sa.PrimaryKeyConstraint('loanConditionID')
    )
    op.create_table('LoanOffer',
    sa.Column('loanOfferID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loanAdvertisementID', sa.Integer(), nullable=False),
    sa.Column('lenderID', sa.Integer(), nullable=False),
    sa.Column('debtorID', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=False),
    sa.Column('dueDate', sa.DateTime(), nullable=False),
    sa.Column('paymentFrequency', sa.Integer(), nullable=False),
    sa.Column('offerStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['debtorID'], ['Debtor.debtorID'], ),
    sa.ForeignKeyConstraint(['lenderID'], ['Lender.lenderID'], ),
    sa.ForeignKeyConstraint(['loanAdvertisementID'], ['LoanAdvertisement.loanAdvertisementID'], ),
    sa.ForeignKeyConstraint(['offerStatus'], ['OfferStatus.offerStatusID'], ),
    sa.ForeignKeyConstraint(['paymentFrequency'], ['PaymentFrequency.paymentFrequencyID'], ),
    sa.PrimaryKeyConstraint('loanOfferID')
    )
    op.create_table('Transaction',
    sa.Column('transactionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loanAdvertisementID', sa.Integer(), nullable=False),
    sa.Column('lenderID', sa.Integer(), nullable=False),
    sa.Column('debtorID', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('originalAmount', sa.Numeric(), nullable=False),
    sa.Column('amountDue', sa.Numeric(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=False),
    sa.Column('dueDate', sa.DateTime(), nullable=False),
    sa.Column('paymentFrequency', sa.Integer(), nullable=False),
    sa.Column('transactionStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['debtorID'], ['Debtor.debtorID'], ),
    sa.ForeignKeyConstraint(['lenderID'], ['Lender.lenderID'], ),
    sa.ForeignKeyConstraint(['loanAdvertisementID'], ['LoanAdvertisement.loanAdvertisementID'], ),
    sa.ForeignKeyConstraint(['paymentFrequency'], ['PaymentFrequency.paymentFrequencyID'], ),
    sa.ForeignKeyConstraint(['transactionStatus'], ['TransactionStatus.transactionStatusID'], ),
    sa.PrimaryKeyConstraint('transactionID')
    )
    op.create_table('Contract',
    sa.Column('contractID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transactionID', sa.Integer(), nullable=False),
    sa.Column('contractDocumentLink', sa.String(), nullable=False),
    sa.Column('contractFileName', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['transactionID'], ['Transaction.transactionID'], ),
    sa.PrimaryKeyConstraint('contractID')
    )
    op.create_table('TransactionPayment',
    sa.Column('transactionPaymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transactionID', sa.Integer(), nullable=False),
    sa.Column('amountPaid', sa.Numeric(), nullable=False),
    sa.Column('datePaid', sa.DateTime(), nullable=False),
    sa.Column('paymentStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paymentStatus'], ['PaymentStatus.paymentStatusID'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['Transaction.transactionID'], ),
    sa.PrimaryKeyConstraint('transactionPaymentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TransactionPayment')
    op.drop_table('Contract')
    op.drop_table('Transaction')
    op.drop_table('LoanOffer')
    op.drop_table('LoanConditions')
    op.drop_table('TransactionStatus')
    op.drop_table('PaymentStatus')
    op.drop_table('PaymentFrequency')
    op.drop_table('OfferStatus')
    op.drop_table('LoanAdvertisement')
    # ### end Alembic commands ###
