"""empty message

Revision ID: 36cab18942a7
Revises: 95c18fef782c
Create Date: 2023-09-10 22:36:55.096932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cab18942a7'
down_revision = '95c18fef782c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offerStatusID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('LoanOffer_offerStatus_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'OfferStatus', ['offerStatusID'], ['offerStatusID'])
        batch_op.drop_column('offerStatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offerStatus', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('LoanOffer_offerStatus_fkey', 'OfferStatus', ['offerStatus'], ['offerStatusID'])
        batch_op.drop_column('offerStatusID')

    # ### end Alembic commands ###
