"""empty message

Revision ID: 63f808a282d0
Revises: bd551b72aca0
Create Date: 2023-09-06 14:48:58.500141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f808a282d0'
down_revision = 'bd551b72aca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dicom',
    sa.Column('dicomID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dicomDocumentLink', sa.String(), nullable=False),
    sa.Column('dicomFileName', sa.String(length=50), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('dicomID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dicom')
    # ### end Alembic commands ###
