"""empty message

Revision ID: 81baff886938
Revises: 21333208f42d
Create Date: 2023-09-15 00:22:39.546059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81baff886938'
down_revision = '21333208f42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanAdvertisement', schema=None) as batch_op:
        batch_op.drop_constraint('LoanAdvertisement_negotiable_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanAdvertisement', schema=None) as batch_op:
        batch_op.create_unique_constraint('LoanAdvertisement_negotiable_key', ['negotiable'])

    # ### end Alembic commands ###
