"""empty message

Revision ID: 84b79b342ae8
Revises: b2a3afaff8a2
Create Date: 2023-09-11 17:06:07.746271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b79b342ae8'
down_revision = 'b2a3afaff8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('bankDetailsID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankDetailsID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('bankID')

    # ### end Alembic commands ###
