"""empty message

Revision ID: 95c18fef782c
Revises: c8a79f2d9458
Create Date: 2023-09-10 22:35:36.510959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c18fef782c'
down_revision = 'c8a79f2d9458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
