"""empty message

Revision ID: a110d2d51535
Revises: 17a6707d6913
Create Date: 2023-09-11 17:18:18.757104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a110d2d51535'
down_revision = '17a6707d6913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.alter_column('bankNameID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('accountTypeID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.alter_column('accountTypeID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bankNameID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
