"""empty message

Revision ID: a8589637df4e
Revises: 
Create Date: 2023-09-07 13:57:41.593417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8589637df4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('profilePictureLink', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('BankDetails',
    sa.Column('bankID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bankName', sa.String(), nullable=False),
    sa.Column('bankCardNumber', sa.String(length=16), nullable=False),
    sa.Column('bankAccountNumber', sa.String(length=8), nullable=False),
    sa.Column('bankSortCode', sa.String(length=6), nullable=False),
    sa.Column('bankIssueDate', sa.Date(), nullable=False),
    sa.Column('bankExpiryDate', sa.Date(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('bankID')
    )
    op.create_table('Debtor',
    sa.Column('debtorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('debtorID')
    )
    op.create_table('Dicom',
    sa.Column('dicomID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dicomDocumentLink', sa.String(), nullable=False),
    sa.Column('dicomFileName', sa.String(length=50), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('dicomID')
    )
    op.create_table('GoogleOAuth',
    sa.Column('googleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('googleOAuthID', sa.String(), nullable=False),
    sa.Column('googleName', sa.String(), nullable=False),
    sa.Column('googleProfilePicture', sa.String(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('googleID'),
    sa.UniqueConstraint('googleOAuthID')
    )
    op.create_table('Identity',
    sa.Column('identityID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identityNumber', sa.String(length=20), nullable=False),
    sa.Column('identityDocumentLink', sa.String(), nullable=False),
    sa.Column('identityFileName', sa.String(length=50), nullable=False),
    sa.Column('identityType', sa.String(length=15), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('identityID')
    )
    op.create_table('Lender',
    sa.Column('lenderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('lenderID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lender')
    op.drop_table('Identity')
    op.drop_table('GoogleOAuth')
    op.drop_table('Dicom')
    op.drop_table('Debtor')
    op.drop_table('BankDetails')
    op.drop_table('User')
    # ### end Alembic commands ###
