"""empty message

Revision ID: b2a3afaff8a2
Revises: 2db5f6aa9a2c
Create Date: 2023-09-11 15:36:09.805448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a3afaff8a2'
down_revision = '2db5f6aa9a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.alter_column('bankNameID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('accountTypeID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BankDetails', schema=None) as batch_op:
        batch_op.alter_column('accountTypeID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bankNameID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
