"""empty message

Revision ID: c8a79f2d9458
Revises: 2fda5e7e218e
Create Date: 2023-09-10 21:57:54.573707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a79f2d9458'
down_revision = '2fda5e7e218e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.drop_constraint('LoanOffer_lenderID_fkey', type_='foreignkey')
        batch_op.drop_column('lenderID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenderID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('LoanOffer_lenderID_fkey', 'Lender', ['lenderID'], ['lenderID'])

    # ### end Alembic commands ###
