"""empty message

Revision ID: d9448e45f579
Revises: 36cab18942a7
Create Date: 2023-09-10 23:45:41.145487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9448e45f579'
down_revision = '36cab18942a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenderID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Lender', ['lenderID'], ['lenderID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LoanOffer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lenderID')

    # ### end Alembic commands ###
